import { User, DoctorProfile, DoctorSchedule, Appointment, MedicalRecord, SystemConfig, SecurityAuditLog } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_pat_01',
    phone: '0912345678',
    fullName: 'Lê Thị Thu Hương',
    role: 'patient',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    dob: '1995-06-15',
    address: '124 Phố Huế, P. Hàng Bông, Q. Hoàn Kiếm, Hà Nội',
    email: 'thuhuong.le@gmail.com',
    createdAt: '2026-01-10T08:00:00Z',
    password: 'Password@123', // Matches special character requirement
  },
  {
    id: 'usr_pat_02',
    phone: '0988112233',
    fullName: 'Trần Văn Mạnh',
    role: 'patient',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    dob: '1988-11-20',
    address: '45 Nguyễn Chí Thanh, Ba Đình, Hà Nội',
    email: 'manh.tran@gmail.com',
    createdAt: '2026-01-15T09:30:00Z',
    password: 'Patient@2026!',
  },
  {
    id: 'usr_doc_01',
    phone: '0987654321',
    fullName: 'BS.CKII Nguyễn Văn An',
    role: 'doctor',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    dob: '1976-03-12',
    address: 'Số 8 Tôn Thất Tùng, Đống Đa, Hà Nội',
    email: 'an.nguyen@jiyuu-clinic.vn',
    createdAt: '2025-12-01T08:00:00Z',
    password: 'Doctor@2026!',
  },
  {
    id: 'usr_doc_02',
    phone: '0978123456',
    fullName: 'ThS.BS Trần Thị Mai',
    role: 'doctor',
    avatar: 'https://images.unsplash.com/photo-1594824813684-938a9a203f3a?w=150&auto=format&fit=crop&q=80',
    dob: '1982-08-25',
    address: '15 Lê Văn Lương, Cầu Giấy, Hà Nội',
    email: 'mai.tran@jiyuu-clinic.vn',
    createdAt: '2025-12-01T08:00:00Z',
    password: 'Doctor@2026!',
  },
  {
    id: 'usr_doc_03',
    phone: '0966789012',
    fullName: 'BSCKI Lê Hoàng Long',
    role: 'doctor',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    dob: '1985-05-18',
    address: '28 Hoàng Cầu, Đống Đa, Hà Nội',
    email: 'long.le@jiyuu-clinic.vn',
    createdAt: '2025-12-05T08:00:00Z',
    password: 'Doctor@2026!',
  },
  {
    id: 'usr_doc_04',
    phone: '0934567890',
    fullName: 'BS Phạm Thu Hà',
    role: 'doctor',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    dob: '1989-10-05',
    address: '72 Trần Phú, Hà Đông, Hà Nội',
    email: 'ha.pham@jiyuu-clinic.vn',
    createdAt: '2025-12-10T08:00:00Z',
    password: 'Doctor@2026!',
  },
  {
    id: 'usr_rec_01',
    phone: '0901234567',
    fullName: 'Ngô Mỹ Linh (Tiếp tân Trưởng)',
    role: 'receptionist',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    dob: '1996-09-02',
    address: 'Số 10 Tràng Thi, Hoàn Kiếm, Hà Nội',
    email: 'tieptan.linh@jiyuu-clinic.vn',
    createdAt: '2025-12-01T08:00:00Z',
    password: 'Recep@2026#',
  },
  {
    id: 'usr_adm_01',
    phone: '0999888777',
    fullName: 'Đoàn Nhật Minh (Quản trị viên)',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    dob: '1980-01-01',
    address: 'Trụ sở JiYuu Clinic - Tòa nhà Healthcare, Hai Bà Trưng, Hà Nội',
    email: 'admin@jiyuu-clinic.vn',
    createdAt: '2025-11-01T08:00:00Z',
    password: 'Admin@2026$',
  },
];

export const INITIAL_DOCTORS: DoctorProfile[] = [
  {
    id: 'doc_01',
    userId: 'usr_doc_01',
    fullName: 'BS.CKII Nguyễn Văn An',
    phone: '0987654321',
    email: 'an.nguyen@jiyuu-clinic.vn',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&auto=format&fit=crop&q=80',
    specialty: 'Khoa Nội',
    experienceYears: 16,
    clinicRoom: 'Phòng khám 201 (Tầng 2)',
    bio: 'Chuyên gia đầu ngành về Tim mạch & Tiêu hoá. Từng giữ vị trí Phó trưởng khoa Nội tại Bệnh viện Bạch Mai. Chuyên khám và điều trị tăng huyết áp, rối loạn lipid, bệnh dạ dày - đại tràng.',
    degrees: ['Bác sĩ Đa khoa - ĐH Y Hà Nội', 'Bác sĩ Chuyên khoa II - Chuyên ngành Nội Tim Mạch'],
    certificates: ['Chứng chỉ Siêu âm tim Doppler mạch máu', 'Chứng chỉ Nội soi tiêu hoá can thiệp'],
    rating: 4.9,
    reviewCount: 142,
    reviews: [
      {
        id: 'rev_1',
        patientName: 'Phạm Hồng Nhung',
        rating: 5,
        comment: 'Bác sĩ An khám rất tận tâm, giải thích bệnh học rõ ràng và kê thuốc dịu êm.',
        date: '2026-02-14',
      },
      {
        id: 'rev_2',
        patientName: 'Nguyễn Quốc Bảo',
        rating: 5,
        comment: 'Phòng khám sạch sẽ, bác sĩ tư vấn lối sống và chế độ ăn rất chi tiết.',
        date: '2026-02-28',
      },
    ],
  },
  {
    id: 'doc_02',
    userId: 'usr_doc_02',
    fullName: 'ThS.BS Trần Thị Mai',
    phone: '0978123456',
    email: 'mai.tran@jiyuu-clinic.vn',
    avatar: 'https://images.unsplash.com/photo-1594824813684-938a9a203f3a?w=200&auto=format&fit=crop&q=80',
    specialty: 'Khoa Ngoại',
    experienceYears: 11,
    clinicRoom: 'Phòng khám 302 (Tầng 3)',
    bio: 'Thạc sĩ Ngoại khoa chuyên ngành Cơ xương khớp và chấn thương chỉnh hình. Nhiều năm kinh nghiệm xử lý thoái hoá khớp gối, viêm gân cột sống, tiểu phẫu ngoại trú.',
    degrees: ['Thạc sĩ Y học Ngoại khoa - ĐH Y Hà Nội', 'Bác sĩ Nội trú Chấn thương Chỉnh hình'],
    certificates: ['Chứng chỉ Tiêm nội khớp dưới hướng dẫn siêu âm', 'Chứng chỉ Chấn thương học thể thao'],
    rating: 4.8,
    reviewCount: 98,
    reviews: [
      {
        id: 'rev_3',
        patientName: 'Đỗ Hữu Thắng',
        rating: 5,
        comment: 'Bác sĩ Mai chẩn đoán gối rất chuẩn, hướng dẫn bài tập vật lý trị liệu hiệu quả.',
        date: '2026-03-01',
      },
    ],
  },
  {
    id: 'doc_03',
    userId: 'usr_doc_03',
    fullName: 'BSCKI Lê Hoàng Long',
    roleSpecialty: 'Khoa Nội',
    phone: '0966789012',
    email: 'long.le@jiyuu-clinic.vn',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=200&auto=format&fit=crop&q=80',
    specialty: 'Khoa Nội',
    experienceYears: 9,
    clinicRoom: 'Phòng khám 204 (Tầng 2)',
    bio: 'Chuyên gia Nội tổng quát, Hô hấp và Bệnh lý Chuyển hoá (Tiểu đường, Tuyến giáp). Phong cách thăm khám chu đáo, cập nhật phác đồ quốc tế.',
    degrees: ['Bác sĩ Chuyên khoa I Nội khoa - ĐH Y Dược TP.HCM'],
    certificates: ['Chứng chỉ Thăm dò chức năng hô hấp', 'Chứng chỉ Quản lý Đái tháo đường'],
    rating: 4.7,
    reviewCount: 85,
    reviews: [],
  } as any,
  {
    id: 'doc_04',
    userId: 'usr_doc_04',
    fullName: 'BS Phạm Thu Hà',
    phone: '0934567890',
    email: 'ha.pham@jiyuu-clinic.vn',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&auto=format&fit=crop&q=80',
    specialty: 'Chuyên khoa Khác',
    experienceYears: 8,
    clinicRoom: 'Phòng khám 105 (Tầng 1)',
    bio: 'Bác sĩ phụ trách Chuyên khoa Tai Mũi Họng và Da Liễu cơ bản. Sử dụng hệ thống nội soi ống mềm hiện đại không đau, khám phát hiện sớm viêm xoang, polyp và các bệnh dị ứng.',
    degrees: ['Bác sĩ Đa khoa - ĐH Y Hà Nội', 'Định hướng Chuyên khoa Tai Mũi Họng'],
    certificates: ['Chứng chỉ Nội soi Tai Mũi Họng can thiệp', 'Chứng chỉ Laser Thẩm mỹ & Da liễu'],
    rating: 4.9,
    reviewCount: 114,
    reviews: [],
  },
];

// Seed Schedules for current month and upcoming weeks
export const INITIAL_SCHEDULES: DoctorSchedule[] = [
  {
    id: 'sch_01',
    doctorId: 'doc_01',
    doctorName: 'BS.CKII Nguyễn Văn An',
    specialty: 'Khoa Nội',
    date: new Date().toISOString().split('T')[0], // Today
    startTime: '08:00',
    endTime: '12:00',
    shiftType: 'Ca sáng (08:00 - 12:00)',
    clinicRoom: 'Phòng khám 201 (Tầng 2)',
    status: 'approved',
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'sch_02',
    doctorId: 'doc_01',
    doctorName: 'BS.CKII Nguyễn Văn An',
    specialty: 'Khoa Nội',
    date: new Date().toISOString().split('T')[0], // Today
    startTime: '13:30',
    endTime: '17:30',
    shiftType: 'Ca chiều (13:30 - 17:30)',
    clinicRoom: 'Phòng khám 201 (Tầng 2)',
    status: 'approved',
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'sch_03',
    doctorId: 'doc_02',
    doctorName: 'ThS.BS Trần Thị Mai',
    specialty: 'Khoa Ngoại',
    date: new Date().toISOString().split('T')[0],
    startTime: '08:00',
    endTime: '12:00',
    shiftType: 'Ca sáng (08:00 - 12:00)',
    clinicRoom: 'Phòng khám 302 (Tầng 3)',
    status: 'approved',
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'sch_04',
    doctorId: 'doc_04',
    doctorName: 'BS Phạm Thu Hà',
    specialty: 'Chuyên khoa Khác',
    date: new Date().toISOString().split('T')[0],
    startTime: '13:30',
    endTime: '17:30',
    shiftType: 'Ca chiều (13:30 - 17:30)',
    clinicRoom: 'Phòng khám 105 (Tầng 1)',
    status: 'approved',
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'sch_05',
    doctorId: 'doc_01',
    doctorName: 'BS.CKII Nguyễn Văn An',
    specialty: 'Khoa Nội',
    date: getOffsetDateString(1), // Tomorrow
    startTime: '08:00',
    endTime: '12:00',
    shiftType: 'Ca sáng (08:00 - 12:00)',
    clinicRoom: 'Phòng khám 201 (Tầng 2)',
    status: 'approved',
    createdAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'sch_06',
    doctorId: 'doc_02',
    doctorName: 'ThS.BS Trần Thị Mai',
    specialty: 'Khoa Ngoại',
    date: getOffsetDateString(2),
    startTime: '13:30',
    endTime: '17:30',
    shiftType: 'Ca chiều (13:30 - 17:30)',
    clinicRoom: 'Phòng khám 302 (Tầng 3)',
    status: 'pending', // Pending receptionist approval demo
    changeReason: 'Xin đăng ký tăng cường thêm ca chiều để phục vụ khám sàng lọc cơ xương khớp',
    notes: 'Đã trao đổi miệng với Trưởng khoa',
    createdAt: '2026-02-18T10:00:00Z',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt_01',
    bookingCode: 'JY-2026-0881',
    patientUserId: 'usr_pat_01',
    patientName: 'Lê Thị Thu Hương',
    patientPhone: '0912345678',
    patientDob: '1995-06-15',
    patientAddress: '124 Phố Huế, P. Hàng Bông, Q. Hoàn Kiếm, Hà Nội',
    isRelativeBooking: false,
    reason: 'Đau tức vùng ngực trái khi vận động kèm khó thở nhẹ vào buổi sáng',
    specialty: 'Khoa Nội',
    doctorId: 'doc_01',
    doctorName: 'BS.CKII Nguyễn Văn An',
    clinicRoom: 'Phòng khám 201 (Tầng 2)',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '09:00',
    status: 'arrived', // Already arrived at clinic! Doctor will receive instant exam trigger
    createdAt: '2026-02-15T08:30:00Z',
    arrivedAt: '2026-02-16T08:50:00Z',
  },
  {
    id: 'apt_02',
    bookingCode: 'JY-2026-0882',
    patientUserId: 'usr_pat_01',
    patientName: 'Nguyễn Văn Hùng (Bố)',
    patientPhone: '0903456789',
    patientDob: '1962-04-10',
    patientAddress: '124 Phố Huế, P. Hàng Bông, Q. Hoàn Kiếm, Hà Nội',
    isRelativeBooking: true,
    relativeName: 'Nguyễn Văn Hùng',
    relativePhone: '0903456789',
    relationType: 'Bố đẻ',
    reason: 'Tái khám huyết áp và đau khớp gối đi lại khó khăn',
    specialty: 'Khoa Ngoại',
    doctorId: 'doc_02',
    doctorName: 'ThS.BS Trần Thị Mai',
    clinicRoom: 'Phòng khám 302 (Tầng 3)',
    appointmentDate: getOffsetDateString(1),
    appointmentTime: '10:30',
    status: 'confirmed',
    createdAt: '2026-02-16T14:15:00Z',
  },
  {
    id: 'apt_03',
    bookingCode: 'JY-2026-0883',
    patientUserId: 'usr_pat_02',
    patientName: 'Trần Văn Mạnh',
    patientPhone: '0988112233',
    patientDob: '1988-11-20',
    patientAddress: '45 Nguyễn Chí Thanh, Ba Đình, Hà Nội',
    isRelativeBooking: false,
    reason: 'Viêm họng hạt kéo dài, nuốt vướng và sốt nhẹ về chiều',
    specialty: 'Chuyên khoa Khác',
    doctorId: 'doc_04',
    doctorName: 'BS Phạm Thu Hà',
    clinicRoom: 'Phòng khám 105 (Tầng 1)',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '14:00',
    status: 'confirmed',
    createdAt: '2026-02-14T09:00:00Z',
  },
];

export const INITIAL_MEDICAL_RECORDS: MedicalRecord[] = [
  {
    id: 'rec_01',
    recordCode: 'BA-2026-0038',
    appointmentId: 'apt_past_01',
    patientUserId: 'usr_pat_01',
    patientName: 'Lê Thị Thu Hương',
    patientDob: '1995-06-15',
    patientPhone: '0912345678',
    patientAddress: '124 Phố Huế, P. Hàng Bông, Q. Hoàn Kiếm, Hà Nội',
    doctorId: 'doc_01',
    doctorName: 'BS.CKII Nguyễn Văn An',
    doctorSignature: 'BS.CKII Nguyễn Văn An (Xác thực điện tử JiYuu PK)',
    examDate: '2026-01-20 09:30',
    clinicRoom: 'Phòng khám 201 (Tầng 2)',
    symptoms: 'Ợ hơi, ợ chua nhiều sau ăn, đau âm ỉ thượng vị, mệt mỏi chán ăn.',
    diagnosis: 'Viêm trợt niêm mạc hang vị dạ dày / Trào ngược dạ dày thực quản độ A',
    treatment: 'Điều trị nội khoa bằng thuốc giảm tiết acid, bảo vệ niêm mạc và điều chỉnh lối sống không ăn cay nóng.',
    prescriptions: [
      {
        id: 'p_1',
        medicineName: 'Esomeprazole 40mg (Nexium)',
        dosage: '40mg',
        quantity: '28 viên',
        usageInstruction: 'Uống 1 viên trước bữa ăn sáng 30 phút, liệu trình 4 tuần',
      },
      {
        id: 'p_2',
        medicineName: 'Gaviscon Dual Action',
        dosage: '10ml',
        quantity: '20 gói',
        usageInstruction: 'Uống 1 gói sau bữa ăn chính và trước khi đi ngủ khi có cảm giác ợ chua',
      },
    ],
    followUpDate: '2026-02-25',
    status: 'treating', // Đang chữa trị
    createdAt: '2026-01-20T10:15:00Z',
    notes: 'Bệnh nhân tái khám sau 4 tuần hoặc tái khám sớm nếu có nôn máu hay sút cân.',
  },
];

export const INITIAL_SYSTEM_CONFIG: SystemConfig = {
  clinicName: 'Phòng Khám Đa Khoa Quốc Tế JiYuu',
  address: 'Số 88 Phố Bà Triệu, Phường Hàng Bài, Quận Hoàn Kiếm, Hà Nội',
  phone: '1900 6868 - 024 3988 9999',
  email: 'contact@jiyuu-clinic.vn',
  cancellationHoursMin: 4, // Yêu cầu: Huỷ lịch trước thời gian khám ít nhất 4 tiếng
  workingHoursStart: '08:00',
  workingHoursEnd: '21:00',
  allowConcurrentCheck: true,
  securityAuditEnabled: true,
};

export const INITIAL_AUDIT_LOGS: SecurityAuditLog[] = [
  {
    id: 'log_01',
    timestamp: '2026-02-15 08:30:12',
    userId: 'usr_pat_01',
    userRole: 'patient',
    userName: 'Lê Thị Thu Hương',
    action: 'ĐẶT_LỊCH_KHÁM',
    details: 'Khởi tạo lịch khám mới JY-2026-0881 với Bác sĩ Nguyễn Văn An',
    ipAddress: '113.190.234.12',
  },
  {
    id: 'log_02',
    timestamp: '2026-02-16 08:50:45',
    userId: 'usr_rec_01',
    userRole: 'receptionist',
    userName: 'Ngô Mỹ Linh',
    action: 'QUÉT_QR_TIẾP_NHẬN',
    details: 'Xác nhận bệnh nhân Lê Thị Thu Hương đến khám, gửi thông báo đến Bác sĩ Nguyễn Văn An',
    ipAddress: '192.168.1.105 (POS Station 01)',
  },
];

function getOffsetDateString(daysOffset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().split('T')[0];
}
